name: fit_perfect_v2
description: A new Flutter project.
publish_to: "none"          # Remove if you plan to publish on pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

# ──────────────── regular runtime dependencies ────────────────
dependencies:
  flutter:
    sdk: flutter

  # ► UI / icons
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  flutter_riverpod: ^2.6.1
  provider: ^6.1.2
  go_router: ^16.0.0
  google_fonts: ^6.1.0
  camera: ^0.10.5+7
  path_provider: ^2.1.3
  amplify_core: ^2.6.1
  amplify_flutter: ^2.6.1
  amplify_storage_s3: ^2.6.1
  video_player: ^2.8.1
  image_picker: ^1.0.7
  share_plus: ^7.0.2

  # ► Amplify 2.x
  amplify_auth_cognito: ^2.6.1
  amplify_secure_storage: ^0.5.8

  # ► Social sign-in
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1

  # ► In-app purchases
  in_app_purchase: ^3.2.0

  # ► Misc
  http: ^1.2.1
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.3.1

  # ► Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  shared_preferences: ^2.2.2

# ──────────────── development-only dependencies ────────────────
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # code-generation
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

# ─────────────────────── Flutter specific ───────────────────────
flutter:
  uses-material-design: true
  generate: true     # enables flutter gen-l10n

  assets:
    # Uncomment as you add real assets
    # - assets/icons/
    # - assets/images/
    # - assets/videos/
